[tools]
"aqua:tinygo-org/tinygo" = "latest"
go = "1.25.0"

[tasks.flash]
run = "tinygo flash --target waveshare-rp2040-zero --size short ./cmd/tiny_monitor"

[tasks.send]
run = "go run ./cmd/send_metrics"
